name: Create PR to Main After Tests

on:
  workflow_run:
    workflows: ["Test MkDocs Build"]
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: features
          base: main
          title: "Automated PR for updates from features"
          body: "This PR merges successfully tested updates from the features branch."
          token: ${{ secrets.GITHUB_TOKEN }}
